### ISSUE TITLE
Optimize encoding of grpc objects transferred across local eventbus

### ISSUE THREAD

**Issue by halajos** [Deutsche-Boerse-Risk/DAVe-MarginLoader#62]
Currently when we send grpc objects over eventbus each object is first serialized into byte[] array, then base64 encoded to be transferred as text (inside JsonObject) and then decoded it on the other end.
This wrapping into JsonObject is interoperable and allows the objects to be used also in a clustered eventbus across the network, but it is not very efficient.
When we use grpc on a local eventbus for internal communication between verticles it would be much more efficient if some binary encoding was used.
One way how to accomplish this (and still be compatible with service proxies which require JsonObject) is to create an immutable subclass of JsonObject around grpc. The immutability avoids copying of objects when delivering locally (inside one jvm), the object reference can be passed back and forth between verticles without any need for encoding and decoding.

**Comment by halajos** [comment]
Related topic for optimizing marshallers of service proxies has been requested in
[https://github.com/vert-x3/vertx-service-proxy/issues/17 ](url) but there is no progress yet.

**Comment by zerola** [comment]
Implemented.
