### ISSUE TITLE
Proper queue names should be used as default

### ISSUE THREAD

**Issue by scholzj** [Deutsche-Boerse-Risk/DAVe-MarginLoader#70]
Production like queue names should be used as defaults:
* broadcast.DAVE.PRISMA_DAVEAccountMargin
* broadcast.DAVE.PRISMA_DAVELiquiGroupMargin
* broadcast.DAVE.PRISMA_DAVELiquiGroupSplitMargin
* broadcast.DAVE.PRISMA_DAVEPoolMargin
* broadcast.DAVE.PRISMA_DAVEPositionReport
* broadcast.DAVE.PRISMA_DAVERiskLimitUtilization

**Comment by zerola** [comment]
Implemented.
